version: '3'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    restart: always
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --import-realm
    environment:
      KC_DB: ${DB_VENDOR}
      KC_DB_URL_HOST: ${DB_HOST}
      KC_DB_URL_DATABASE: ${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_PROFILE_FEATURE_UPLOAD: enabled
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/key.pem
##     Dev Configuration in order to access in HTTP mode
#      KC_HOSTNAME_STRICT: false #deactivate fixed hostname
#      KC_HOSTNAME_STRICT_HTTPS: false #For local access to console admin in start mode
#      KC_HTTP_ENABLED: true
    command: ["-Dkeycloak.profile.feature.token_exchange=enabled
               -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"]
    volumes:
      - ./config.json:/opt/keycloak/data/import/keycloak-config.json
      - ../certificates/${KEYCLOAK_HOST}.cert.pem:/opt/keycloak/conf/cert.pem
      - ../certificates/${KEYCLOAK_HOST}.key.pem:/opt/keycloak/conf/key.pem
    ports:
      - "${KEYCLOAK_HTTPS_PORT}:443"

#    depends_on:
#      - postgres
#
#  postgres:
#    hostname: ${DB_HOST}
#    image: postgres
#    environment:
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - ./db_data:/var/lib/postgresql/data
